[package]
name = "draw"
version = "0.1.0"
edition = "2021"

[dependencies]
base = { path = "../../base" }
bincode = "1"

[build-dependencies]
base-types = { path = "../../base-types" }
serde_json = "1"
bincode = "1"

[[bin]]
name = "draw"
path = "src/main.rs"
